from playwright.sync_api import Playwright, expect

# generated by codegen with command ->  uv run playwright codegen --viewport-size="1920,1080" wikipedia.com
def test_wikipedia_navigation(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(viewport={"width":1920,"height":1080})
    page = context.new_page()
    page.goto("https://www.wikipedia.org/")
    with page.expect_popup() as page1_info:
        page.get_by_role("link", name="Google Play Store").click()
    page1 = page1_info.value
    with page.expect_popup() as page2_info:
        page.get_by_role("link", name="Apple App Store").click()
    page2 = page2_info.value
    expect(page2.get_by_role("heading", name="Wikipedia")).to_be_visible()
    expect(page1.get_by_role("link", name="Wikimedia Foundation", exact=True)).to_be_visible()
    page1.close()
    page2.close()
    page.get_by_role("link", name="日本語 1,475,000+ 記事").click()
    expect(page.get_by_role("link", name='閲覧', exact=True).first).to_be_visible()

    # ---------------------
    context.close()
    browser.close()



