[project]
name = "tzafon-braintrust"
version = "0.1.0"
description = "Tzafon Braintrust integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autoevals>=0.0.130",
    "braintrust>=0.3.15",
    "dotenv>=0.9.9",
    "openai>=2.14.0",
    "playwright>=1.57.0",
    "tzafon>=2.9.0",
]

[dependency-groups]
dev = [
    "braintrust[cli]>=0.3.15",
]
